<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // PostgreSQL enums generated by Laravel are varchar + CHECK constraints.
        if (DB::getDriverName() === 'pgsql') {
            DB::statement('ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check');
        }
        Schema::table('orders', function (Blueprint $table) {
            $table->string('status')->default('pending')->change();
            $table->string('delivery_type')->default('standard');
            $table->timestamp('consented_at')->nullable();
            $table->string('consent_version')->nullable();
            $table->timestamp('paid_at')->nullable();
            $table->decimal('refund_amount', 10, 2)->default(0);
        });
        Schema::create('order_drafts', function (Blueprint $table) {
            $table->id();
            $table->string('code', 8)->unique();
            $table->uuid('request_id')->unique();
            $table->string('source');
            $table->json('items');
            $table->string('prisoner_name')->nullable();
            $table->foreignId('institution_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('order_id')->nullable()->unique()->constrained()->nullOnDelete();
            $table->timestamp('expires_at')->index();
            $table->timestamps();
        });
        Schema::create('pilot_events', function (Blueprint $table) {
            $table->id();
            $table->uuid('request_id');
            $table->string('event');
            $table->string('source');
            $table->timestamp('created_at')->useCurrent();
            $table->unique(['request_id', 'event']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('pilot_events');
        Schema::dropIfExists('order_drafts');
        Schema::table('orders', function (Blueprint $table) {
            $table->dropColumn(['delivery_type', 'consented_at', 'consent_version', 'paid_at', 'refund_amount']);
        });
    }
};
